### ISSUE TITLE
[Idea] Offline message propegation using I2P-Bote when all contacts are offline

### ISSUE THREAD

**Issue by rodneyrod** [bounce-chat/bounce-core#1]
In theory, you could use an I2P-Bote like system to serve messages to each other in cases where, a user only has one device and it goes offline, and only has one friend and they're both offline.

**Comment by hkparker** [comment]
That would probably work but I've considered such things outside the scope of the project for the time being.  There's a few complications that come from systems that require storage on the network, namely that you have to choose to either let others use a potentially large amount of storage space, or messages stored on the network could be deleted faster than expected if a lot of data is added to the network quickly.  Both cases enable someone succeeding in a sibyl attack to influence the behavior of the application.  And there's the computational/network overhead.

But those all seem more or less solvable in the long run, the real issue is I can't rely on lots of contributions and I know that I can't reasonably plan on completing such a wide feature set on my own.  So once I'm satisfied with everything else I have planned I might look into something like this, but I don't see that happening in the foreseeable future.  If a PR is submitted with a well tested integration of a system like this I would want to merge it in, but that's a long ways out.

Going to close this, if you have any ideas on how we might be able to pull this off in a simpler way please open another issue.
